export const ENTITIES = {
  energy: {
    power: "sensor.tibber_pulse_mount_cleltze_leistung",
    dailyConsumption: "sensor.tibber_pulse_mount_cleltze_kumulierter_verbrauch",
    dailyCost: "sensor.tibber_pulse_mount_cleltze_kumulierte_kosten",
    monthlyCost: "sensor.mount_cleltze_monatliche_kosten",
    monthlyConsumption: "sensor.mount_cleltze_monatlicher_nettoverbrauch",
    avgPower: "sensor.tibber_pulse_mount_cleltze_durchschnittliche_leistung",
    maxPower: "sensor.tibber_pulse_mount_cleltze_maximale_leistung",
    minPower: "sensor.tibber_pulse_mount_cleltze_minimale_leistung",
    spotPrice: "sensor.epex_spot_data_market_price",
    spotLowest: "sensor.epex_spot_data_lowest_price",
    spotHighest: "sensor.epex_spot_data_highest_price",
    spotAverage: "sensor.epex_spot_data_average_price",
    spotQuantile: "sensor.epex_spot_data_quantile",
    spotRank: "sensor.epex_spot_data_rank",
    voltageL1: "sensor.tibber_pulse_mount_cleltze_spannung_l1",
    voltageL2: "sensor.tibber_pulse_mount_cleltze_spannung_l2",
    voltageL3: "sensor.tibber_pulse_mount_cleltze_spannung_l3",
    currentL1: "sensor.tibber_pulse_mount_cleltze_stromstarke_l1",
    currentL2: "sensor.tibber_pulse_mount_cleltze_stromstarke_l2",
    currentL3: "sensor.tibber_pulse_mount_cleltze_stromstarke_l3",
    hourlyConsumption: "sensor.tibber_pulse_mount_cleltze_kumulierter_verbrauch_aktuelle_stunde",
    hourlyEstimate: "sensor.tibber_pulse_mount_cleltze_geschatzter_verbrauch_aktuelle_stunde",
    meterReading: "sensor.tibber_pulse_mount_cleltze_zahlerstand_verbrauch",
    eveEnergy1Power: "sensor.eve_energy_20ebo8301_leistung",
    eveEnergy2Power: "sensor.eve_energy_20ebo8301_leistung_2",
    shellyPower: "sensor.shelly1pmg4_a085e3bc51c4_switch_0_power",
    trocknerPower: "sensor.shelly1pmg4_48f6eec9de50_leistung",
    waschmaschinePower: "sensor.waschmaschine_leistung",
    tibberPrice: "sensor.mount_cleltze_strompreis",
    tibberDailyCost: "sensor.tibber_pulse_mount_cleltze_kumulierte_kosten",
    co2Intensity: "sensor.electricity_maps_co2_intensitat",
    fossilShare: "sensor.electricity_maps_anteil_fossiler_energietrager",
    // Powercalc individual device power sensors
    appleTvBadPower: "sensor.apple_tv_bad_power",
    appleTvSchlafzimmerPower: "sensor.apple_tv_schlafzimmer_power",
    sonosMoveBuroPower: "sensor.sonos_move_2_buro_power",
    standleuchtePower: "sensor.standleuchte_power",
    fotowandPower: "sensor.fotowand_power",
    tradfriBulb2Power: "sensor.tradfri_bulb_2_power",
    wohnzimmerSpeakerPower: "sensor.wohnzimmer_power",
  },
  car: {
    // Battery & Range
    battery: "sensor.crest_batteriestand",
    batteryLegacy: "sensor.crest_ladezustand",
    range: "sensor.crest_batteriereichweite",
    rangeLegacy: "sensor.crest_geschatzte_verbleibende_reichweite",
    targetCharge: "sensor.crest_soll_ladezustand",
    // Charging
    chargingStatus: "sensor.crest_ladestatus",
    chargingBinary: "binary_sensor.crest_ladestatus",
    plugged: "binary_sensor.crest_stecker",
    cableConnected: "binary_sensor.crest_ladekabel",
    chargeSwitch: "switch.crest_aufladung",
    chargerPower: "sensor.crest_ladegerat_leistung",
    chargerVoltage: "sensor.crest_ladegerat_spannung",
    chargerCurrent: "sensor.crest_ladegerat_stromstarke",
    chargingSpeed: "sensor.crest_ladegeschwindigkeit",
    timeToFull: "sensor.crest_zeit_zum_vollstandigen_aufladen",
    energyAdded: "sensor.crest_ladeenergie_hinzugefugt",
    chargeLimit: "number.crest_ladelimit",
    chargeCurrentSetting: "number.crest_ladestrom",
    // Status & Location
    connectivity: "binary_sensor.crest_konnektivitat",
    awake: "binary_sensor.crest_status",
    userPresent: "binary_sensor.crest_benutzer_anwesend",
    location: "device_tracker.crest_standort",
    // Locks & Covers
    lock: "lock.crest_schloss",
    cableLock: "lock.crest_verriegelung_des_ladekabels",
    trunk: "cover.crest_kofferraum",
    frunk: "cover.crest_front_kofferraum",
    chargePort: "cover.crest_ladeanschluss_klappe",
    windows: "cover.crest_fenster",
    // Doors & Windows (individual)
    doorDriverFront: "binary_sensor.crest_fahrertur_vorne",
    doorDriverRear: "binary_sensor.crest_fahrertur_hinten",
    doorPassengerFront: "binary_sensor.crest_beifahrertur_vorne",
    doorPassengerRear: "binary_sensor.crest_beifahrertur_hinten",
    windowDriverFront: "binary_sensor.crest_fahrerfenster_vorne",
    windowDriverRear: "binary_sensor.crest_fahrerfenster_hinten",
    windowPassengerFront: "binary_sensor.crest_beifahrerfenster_vorne",
    windowPassengerRear: "binary_sensor.crest_beifahrerfenster_hinten",
    // Climate & Comfort
    climate: "climate.crest_klima",
    exteriorTemp: "sensor.crest_aussentemperatur",
    interiorTemp: "sensor.crest_innentemperatur",
    defrost: "switch.crest_entfrosten",
    steeringWheelHeater: "select.crest_lenkradheizung",
    seatHeaterLeft: "select.crest_sitzheizung_vorne_links",
    seatHeaterRight: "select.crest_sitzheizung_vorne_rechts",
    sentryMode: "switch.crest_wachter_modus",
    // Media
    mediaPlayer: "media_player.crest_mediaplayer",
    // Actions
    honk: "button.crest_hupen",
    flashLights: "button.crest_lichthupe",
    wake: "button.crest_wecken",
    // Update
    update: "update.crest_update",
  },
  climate: {
    // Bad — Eve Thermo (Thermostat mit Ventil)
    thermostat: "climate.eve_thermo_20ebp1701",
    badTemp: "sensor.eve_thermo_20ebp1701_temperatur",
    badBattery: "sensor.eve_thermo_20ebp1701_batterie",
    badValve: "sensor.eve_thermo_20ebp1701_ventilstellung",
    // Büro — Eve Thermo Control
    bueroTemp: "sensor.eve_thermo_control_20eck9901_temperatur",
    bueroHumidity: "sensor.eve_thermo_control_20eck9901_luftfeuchtigkeit",
    bueroBattery: "sensor.eve_thermo_control_20eck9901_batterie",
    // Wohnzimmer — Eve Thermo Control
    wohnzimmerTemp: "sensor.eve_thermo_control_20eck9901_temperatur_2",
    wohnzimmerHumidity: "sensor.eve_thermo_control_20eck9901_luftfeuchtigkeit_2",
    wohnzimmerBattery: "sensor.eve_thermo_control_20eck9901_batterie_2",
    // Schlafzimmer — Eve Thermo Control
    schlafzimmerTemp: "sensor.eve_thermo_control_20eck9901_temperatur_3",
    schlafzimmerHumidity: "sensor.eve_thermo_control_20eck9901_luftfeuchtigkeit_3",
    schlafzimmerBattery: "sensor.eve_thermo_control_20eck9901_batterie_3",
  },
  lighting: {
    wohnzimmer: "light.wohnzimmer",
    standleuchte: "light.standleuchte",
    fotowand: "light.fotowand",
    badezimmer: "light.badezimmerlampe",
    tradfriBulb: "light.tradfri_bulb_2",
    blind: "cover.tradfri_blind",
  },
  scenes: {
    entspannen: "scene.wohnzimmer_entspannen",
    hell: "scene.wohnzimmer_hell",
    gedimmt: "scene.wohnzimmer_gedimmt",
    lesen: "scene.wohnzimmer_lesen",
    nachtlicht: "scene.wohnzimmer_nachtlicht",
    konzentrieren: "scene.wohnzimmer_konzentrieren",
    energieTanken: "scene.wohnzimmer_energie_tanken",
    nordlichter: "scene.wohnzimmer_nordlichter",
    fruhlingsbluten: "scene.wohnzimmer_fruhlingsbluten",
    sonnenuntergang: "scene.wohnzimmer_sonnenuntergang_savanne",
    tropendammerung: "scene.wohnzimmer_tropendammerung",
  },
  media: {
    wohnzimmer: "media_player.wohnzimmer",
    buro: "media_player.buro",
    schlafzimmer: "media_player.schlafzimmer",
    bad: "media_player.bad",
    spotify: "media_player.spotify_eike",
  },
  vacuum: {
    entity: "vacuum.q5_max",
    battery: "sensor.q5_max_batterie",
    status: "sensor.q5_max_status",
    currentRoom: "sensor.q5_max_aktueller_raum",
    cleaningArea: "sensor.q5_max_reinigungsbereich",
    cleaningTime: "sensor.q5_max_reinigungszeit",
    cleaningProgress: "sensor.q5_max_reinigungsfortschritt",
    lastCleanStart: "sensor.q5_max_letzter_reinigungsbeginn",
    lastCleanEnd: "sensor.q5_max_letztes_reinigungsende",
    error: "sensor.q5_max_staubsauger_fehler",
    filterRemaining: "sensor.q5_max_verbleibende_filterzeit",
    mainBrushRemaining: "sensor.q5_max_verbleibende_zeit_der_hauptburste",
    sideBrushRemaining: "sensor.q5_max_verbleibende_zeit_der_seitenburste",
    sensorRemaining: "sensor.q5_max_verbleibende_sensorzeit",
    dockFreshWater: "binary_sensor.r2_dreck2_dock_frischwassertank",
    dockDirtyWater: "binary_sensor.r2_dreck2_dock_schmutzwassertank",
    dockError: "sensor.q5_max_dock_dock_fehler",
  },
  general: {
    person: "person.eike_clement",
    weather: "weather.forecast_home",
    sun: "sun.sun",
    presenceEike: "device_tracker.iphone_3",
    presenceSabrina: "device_tracker.iphone",
    doorBuero: "binary_sensor.eve_door_20ebn9901_tur",
    doorWohnzimmer: "binary_sensor.eve_door_20ebn9901_tur_2",
    doorSchlafzimmer: "binary_sensor.eve_door_20ebn9901_tur_3",
    doorBad: "binary_sensor.eve_door_20ebn9901_tur_4",
    nukiOpener: "device_tracker.nuki_opener_2d1ebaea",
  },
  household: {
    dishwasher: "device_tracker.siemens_dishwasher_405100396091020532",
    toothbrush1: "sensor.io_series_6_7_cb84",
    toothbrush1Battery: "sensor.io_series_6_7_cb84_batterie",
    toothbrush2: "sensor.smart_series_7000_2959",
    toothbrush2Battery: "sensor.smart_series_7000_2959_batterie",
  },
  network: {
    downloadSpeed: "sensor.fritz_box_7530_download_durchsatz",
    uploadSpeed: "sensor.fritz_box_7530_upload_durchsatz",
    cpuTemp: "sensor.fritz_box_7530_cpu_temperatur",
    connectionStatus: "binary_sensor.fritz_box_7530_verbindung",
    maxDownload: "sensor.fritz_box_7530_maximaler_download_durchsatz_der_verbindung",
    maxUpload: "sensor.fritz_box_7530_maximaler_upload_durchsatz_der_verbindung",
    gbReceived: "sensor.fritz_box_7530_gb_empfangen",
    gbSent: "sensor.fritz_box_7530_gb_gesendet",
  },
  pets: {
    // Nala
    nalaTracker: "device_tracker.nala_tracker",
    nalaBattery: "sensor.nala_tracker_batterie",
    nalaStatus: "sensor.nala_tracker_status",
    nalaActivity: "sensor.nala_aktivitatszeit",
    nalaRest: "sensor.nala_ruhezeit",
    nalaGoal: "sensor.nala_tagliches_ziel",
    nalaDaySleep: "sensor.nala_tagesschlaf",
    nalaNightSleep: "sensor.nala_nachtschlaf",
    nalaCharging: "binary_sensor.nala_tracker_batterie_wird_geladen",
    nalaPowerSaving: "binary_sensor.nala_tracker_energiesparmodus",
    // Biene
    bieneTracker: "device_tracker.biene_tracker",
    bieneBattery: "sensor.biene_tracker_batterie",
    bieneStatus: "sensor.biene_tracker_status",
    bieneActivity: "sensor.biene_aktivitatszeit",
    bieneRest: "sensor.biene_ruhezeit",
    bieneGoal: "sensor.biene_tagliches_ziel",
    bieneDaySleep: "sensor.biene_tagesschlaf",
    bieneNightSleep: "sensor.biene_nachtschlaf",
    bieneCharging: "binary_sensor.biene_tracker_batterie_wird_geladen",
    bienePowerSaving: "binary_sensor.biene_tracker_energiesparmodus",
  },
} as const;
